version: "3.5"

volumes:
  wordpress:
    driver: local
  mariadb:
    driver: local

networks:
  inception:

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN=${DOMAIN}
        - CERT_PATH=${CERT_PATH}
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      args:
        - DOMAIN=${DOMAIN}
        - TITLE=${TITLE}
        - DB_NAME=${DB_NAME}
        - DB_HOST=${DB_HOST}
        - ADMIN_USER=${ADMIN_USER}
        - ADMIN_PASS=${ADMIN_PASS}
        - ADMIN_EMAIL=${ADMIN_EMAIL}
        - USER=${USER}
        - USER_PASS=${USER_PASS}
        - USER_EMAIL=${USER_EMAIL}
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - DB_NAME=${DB_NAME}
        - ADMIN_USER=${ADMIN_USER}
        - ADMIN_PASS=${ADMIN_PASS}
        - ROOT_PASS=${ROOT_PASS}
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5
